version: '3.8'

services:
  # OpenLearn API Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: openlearn-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS}
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          # Allocate 600MB for the app (leaving 350MB for system + Postgres)
          memory: 600M
          cpus: '1.2'
        reservations:
          memory: 400M
          cpus: '0.8'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - app-logs:/app/logs
      - app-uploads:/app/uploads
    networks:
      - openlearn-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  # PostgreSQL Database (Lightweight configuration)
  postgres:
    image: postgres:15-alpine
    container_name: openlearn-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-openlearn_prod}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Optimize Postgres for low memory
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Custom PostgreSQL config for low memory
      - ./postgres-low-memory.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    networks:
      - openlearn-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 60s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          # Allocate 250MB for Postgres
          memory: 250M
          cpus: '0.6'
        reservations:
          memory: 150M
          cpus: '0.2'
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  openlearn-network:
    driver: bridge

volumes:
  app-logs:
    driver: local
  app-uploads:
    driver: local
  postgres_data:
    driver: local
