name: Staging Deployment

on:
  push:
    branches: [ develop ]

env:
  NODE_VERSION: '18'

jobs:
  build:
    name: Build Develop Branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build TypeScript
      run: npm run build

  notify:
    name: Notify Develop Status
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    
    steps:
    - name: Success Notification
      if: needs.build.result == 'success'
      run: |
        echo "Develop branch build passed!"
        echo "Ready to create PR to main branch"

    - name: Failure Notification
      if: needs.build.result == 'failure'
      run: |
        echo "Develop branch build failed!"
        echo "Please fix the issues before creating PR to main"
