name: OpenLearn CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: '18'

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: openlearn_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Setup test database
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/openlearn_test
        run: npx prisma migrate deploy

      - name: Build TypeScript
        run: npm run build

      - name: Install production dependencies only
        run: |
          npm ci --only=production --ignore-scripts
          npx prisma generate

      - name: Create deployment package
        run: |
          mkdir -p deploy-package
          cp -r dist deploy-package/
          cp -r node_modules deploy-package/
          cp -r prisma deploy-package/
          cp package.json deploy-package/
          cp package-lock.json deploy-package/
          cp docker-compose.yml deploy-package/
          cp Dockerfile.production deploy-package/
          cp .dockerignore deploy-package/
          cp -r src/templates deploy-package/templates 2>/dev/null || echo "No templates directory"

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: deploy-package/
          retention-days: 7

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production

    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: deployment-package
          path: ./deploy-package

      - name: Create deployment archive
        run: |
          echo "Deployment package contents:"
          ls -lah deploy-package/
          cd deploy-package
          # Verify node_modules exists and has content
          if [ ! -d "node_modules" ]; then
            echo "ERROR: node_modules not found in deployment package!"
            exit 1
          fi
          echo "node_modules size: $(du -sh node_modules | cut -f1)"
          echo "node_modules file count: $(find node_modules -type f | wc -l)"
          tar -czf ../deployment.tar.gz .
          cd ..
          echo "Archive contents (first 30 lines):"
          tar -tzf deployment.tar.gz | head -30
          echo "Archive size: $(du -h deployment.tar.gz | cut -f1)"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy deployment package to server
        run: |
          scp -o StrictHostKeyChecking=no deployment.tar.gz \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/deployment-${{ github.sha }}.tar.gz

      - name: Create deployment script
        run: |
          cat > deploy-to-server.sh << 'EOF'
          #!/bin/bash
          set -e

          DEPLOYMENT_SHA="${1:-unknown}"
          DEPLOY_DIR="/home/ubuntu/openlearn-backend"
          BACKUP_FILE="$DEPLOY_DIR/deployment-backup.tar.gz"

          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Starting deployment of commit $DEPLOYMENT_SHA"

          # Navigate to deployment directory
          cd "$DEPLOY_DIR"

          # Verify .env file exists
          if [ ! -f "$DEPLOY_DIR/.env" ]; then
            echo "ERROR: .env file not found at $DEPLOY_DIR/.env"
            exit 1
          fi

          # Backup current deployment files (only the built artifacts)
          if [ -d "dist" ] && [ -f "docker-compose.yml" ]; then
            echo "[$(date +'%Y-%m-%d %H:%M:%S')] Backing up current deployment..."
            tar -czf "$BACKUP_FILE.new" dist/ node_modules/ package.json package-lock.json docker-compose.yml Dockerfile.production prisma/ templates/ 2>/dev/null || true
            mv "$BACKUP_FILE.new" "$BACKUP_FILE" || true
          fi

          # Stop all running containers
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Stopping containers..."
          docker-compose --env-file "$DEPLOY_DIR/.env" down 2>/dev/null || true
          
          # Stop any lingering containers
          docker ps -a --format '{{.Names}}' | grep -E 'openlearn-backend' | xargs -r docker stop 2>/dev/null || true
          docker ps -a --format '{{.Names}}' | grep -E 'openlearn-backend' | xargs -r docker rm 2>/dev/null || true

          # Extract new deployment (overwrites existing files)
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Extracting new deployment..."
          tar -xzf "/tmp/deployment-$DEPLOYMENT_SHA.tar.gz" -C "$DEPLOY_DIR"
          rm "/tmp/deployment-$DEPLOYMENT_SHA.tar.gz"

          # Verify extracted files
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Verifying extracted files..."
          if [ ! -d "$DEPLOY_DIR/dist" ]; then
            echo "ERROR: dist directory not found after extraction!"
            ls -la "$DEPLOY_DIR/"
            exit 1
          fi
          if [ ! -d "$DEPLOY_DIR/node_modules" ]; then
            echo "ERROR: node_modules directory not found after extraction!"
            ls -la "$DEPLOY_DIR/"
            exit 1
          fi
          if [ ! -f "$DEPLOY_DIR/Dockerfile.production" ]; then
            echo "ERROR: Dockerfile.production not found after extraction!"
            ls -la "$DEPLOY_DIR/"
            exit 1
          fi
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] All deployment files verified"

          # Verify critical environment variables
          if ! grep -q "JWT_SECRET" "$DEPLOY_DIR/.env"; then
            echo "ERROR: .env file appears to be invalid"
            exit 1
          fi
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Environment file verified"

          # Clear Docker build cache to ensure fresh build
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Clearing Docker build cache..."
          docker builder prune -f || true

          # Build Docker image with pre-built artifacts (no cache to ensure .dockerignore is read)
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Building Docker image..."
          docker-compose --env-file "$DEPLOY_DIR/.env" build --no-cache app

          # Start all services with explicit env file
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Starting all services..."
          docker-compose --env-file "$DEPLOY_DIR/.env" up -d

          # Wait for services to start
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Waiting for services to start..."
          sleep 10

          # Check if app container is running or crashing
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Checking container status..."
          docker-compose --env-file "$DEPLOY_DIR/.env" ps
          
          # Show app logs for debugging
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] App container logs:"
          docker-compose --env-file "$DEPLOY_DIR/.env" logs --tail=50 app || true

          # Wait a bit more for app to stabilize
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Waiting for app to stabilize..."
          sleep 20

          # Check if app container is running
          if ! docker-compose --env-file "$DEPLOY_DIR/.env" ps app | grep -q "Up"; then
            echo "[$(date +'%Y-%m-%d %H:%M:%S')] ERROR: App container is not running!"
            echo "[$(date +'%Y-%m-%d %H:%M:%S')] Container status:"
            docker-compose --env-file "$DEPLOY_DIR/.env" ps
            echo "[$(date +'%Y-%m-%d %H:%M:%S')] Full logs:"
            docker-compose --env-file "$DEPLOY_DIR/.env" logs app
            
            # Attempt rollback if backup exists
            if [ -f "$BACKUP_FILE" ]; then
              echo "[$(date +'%Y-%m-%d %H:%M:%S')] Attempting rollback..."
              docker-compose --env-file "$DEPLOY_DIR/.env" down
              tar -xzf "$BACKUP_FILE" -C "$DEPLOY_DIR"
              docker-compose --env-file "$DEPLOY_DIR/.env" up -d
            fi
            exit 1
          fi

          # Run database migrations
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Running database migrations..."
          if ! docker-compose --env-file "$DEPLOY_DIR/.env" exec -T app npx prisma migrate deploy; then
            echo "[$(date +'%Y-%m-%d %H:%M:%S')] Migration failed!"
            
            # Attempt rollback if backup exists
            if [ -f "$BACKUP_FILE" ]; then
              echo "[$(date +'%Y-%m-%d %H:%M:%S')] Attempting rollback..."
              docker-compose --env-file "$DEPLOY_DIR/.env" down
              tar -xzf "$BACKUP_FILE" -C "$DEPLOY_DIR"
              docker-compose --env-file "$DEPLOY_DIR/.env" up -d
            fi
            exit 1
          fi

          # Perform health checks
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Performing health checks..."
          for i in {1..10}; do
            if curl -f -s http://localhost:3000/health > /dev/null 2>&1; then
              echo "[$(date +'%Y-%m-%d %H:%M:%S')] Health check passed!"
              echo "[$(date +'%Y-%m-%d %H:%M:%S')] Deployment successful!"
              echo "[$(date +'%Y-%m-%d %H:%M:%S')] Deployed commit: $DEPLOYMENT_SHA"
              exit 0
            fi
            echo "[$(date +'%Y-%m-%d %H:%M:%S')] Health check attempt $i/10 failed, retrying..."
            sleep 10
          done

          # Health check failed - attempt rollback
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Health check failed after 10 attempts"
          
          docker-compose --env-file "$DEPLOY_DIR/.env" down
          
          if [ -f "$BACKUP_FILE" ]; then
            echo "[$(date +'%Y-%m-%d %H:%M:%S')] Attempting rollback..."
            tar -xzf "$BACKUP_FILE" -C "$DEPLOY_DIR"
            docker-compose --env-file "$DEPLOY_DIR/.env" up -d
            echo "[$(date +'%Y-%m-%d %H:%M:%S')] Rollback completed"
          else
            echo "[$(date +'%Y-%m-%d %H:%M:%S')] No backup available for rollback"
          fi
          
          echo "[$(date +'%Y-%m-%d %H:%M:%S')] Deployment failed - check logs:"
          docker-compose --env-file "$DEPLOY_DIR/.env" logs --tail=50 app
          
          exit 1
          EOF

          chmod +x deploy-to-server.sh

      - name: Copy deployment script to server
        run: |
          scp -o StrictHostKeyChecking=no deploy-to-server.sh \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/deploy-${{ github.sha }}.sh

      - name: Execute deployment
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "bash /tmp/deploy-${{ github.sha }}.sh ${{ github.sha }}"

      - name: Cleanup deployment script
        if: always()
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "rm -f /tmp/deploy-${{ github.sha }}.sh" || true

      - name: Display deployment info
        if: success()
        run: |
          echo "Deployment completed successfully"
          echo "Commit: ${{ github.sha }}"
          echo "Deployed to: /home/ubuntu/openlearn-backend/"

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [test, deploy]
    if: always() && github.ref == 'refs/heads/main'

    steps:
      - name: Deployment Success
        if: needs.deploy.result == 'success'
        run: |
          echo "Deployment to production completed"
          echo "App: https://${{ secrets.EC2_HOST }}:3000"
          echo "Health Check: https://${{ secrets.EC2_HOST }}:3000/health"

      - name: Deployment Failure
        if: needs.deploy.result == 'failure'
        run: |
          echo "Deployment to production failed"
          echo "Check logs for details"
